# Generated by Django 3.2.9 on 2021-11-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songsuggestion',
            name='songNumber',
            field=models.IntegerField(unique=True),
        ),
    ]
